// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

type CloudflareEnv = {
  DB: D1Database;
  SPOTIFY_CLIENT_ID: string;
  SPOTIFY_CLIENT_SECRET: string;
  SPOTIFY_REDIRECT_URI: string;
  SPOTIFY_REFRESH_TOKEN: string;
  SPOTIFY_ACCESS_TOKEN: string;
};
